set(ohos ON)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_DEP_INFO_OVERRIDE_VARS ohos)
set(VCPKG_ENV_PASSTHROUGH OHOS_NDK_HOME)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../../scripts/toolchains/ohos.cmake")

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)